//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDgeDet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class kaydet : global::System.Configuration.ApplicationSettingsBase {
        
        private static kaydet defaultInstance = ((kaydet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new kaydet())));
        
        public static kaydet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double gorecedeger5xk {
            get {
                return ((double)(this["gorecedeger5xk"]));
            }
            set {
                this["gorecedeger5xk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double gorecedeger10xk {
            get {
                return ((double)(this["gorecedeger10xk"]));
            }
            set {
                this["gorecedeger10xk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double gorecedeger20xk {
            get {
                return ((double)(this["gorecedeger20xk"]));
            }
            set {
                this["gorecedeger20xk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double gorecedeger50xk {
            get {
                return ((double)(this["gorecedeger50xk"]));
            }
            set {
                this["gorecedeger50xk"] = value;
            }
        }
    }
}
